[package]
name = "tindex"
version = "0.5.6"
authors = ["lcnr/Bastian Kauschke <rust@lcnr.de>"]
description = "`Vec`, slice and bitset with custom index types"
repository = "https://github.com/lcnr/tindex"
license = "MIT"
edition = "2021"
